esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  manual_ip:
    gateway: !secret gateway
    subnet: !secret subnet

  ap:
    password: !secret wifi_ap_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

logger:
  baud_rate: 0

api:

ota:
  password: !secret ota_password

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  #button press
  - platform: gpio
    name: ${name}_button
    pin:
      number: GPIO16
      inverted: true
    on_press:
      - switch.toggle: relay

switch:
  #toggle relay (power output)
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_ON
    id: relay
    name: ${name}_switch
    pin: GPIO14
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

  #toggle relay (usb output)
  - platform: gpio
    id: relay2
    name: ${name}_USB_switch
    pin: GPIO5
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

output:
  #relay state led
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO00
      inverted: true

light:
  #relay state light
  - platform: monochromatic
    output: state_led
    id: led

#red led as status indicator
status_led:
  pin:
    number: GPIO02
    inverted: true

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: ${name}_esphome_version
    hide_timestamp: true
